from gym_throwandpush.envs.mujoco_env_pusher import MujocoEnvPusher2
from gym_throwandpush.envs.pusher2 import Pusher2Env
from gym_throwandpush.envs.pusher2pixel import Pusher2PixelEnv
from gym_throwandpush.envs.pusher2plus import Pusher2PlusEnv
from gym_throwandpush.envs.cheetah2 import Cheetah2Env
from gym_throwandpush.envs.cheetah2pixel import Cheetah2PixelEnv
from gym_throwandpush.envs.cheetah2plus import Cheetah2PlusEnv

# from Berkeley
from gym_throwandpush.envs.pusher3dof import PusherEnv3Dof

from gym_throwandpush.envs.pusher3dof2 import Pusher3Dof2Env
from gym_throwandpush.envs.pusher3dof2plus import Pusher3Dof2Plus
from gym_throwandpush.envs.pusher3dof2lstm import Pusher3Dof2Lstm
from gym_throwandpush.envs.pusher3dof2plus2 import Pusher3Dof2Plus2
from gym_throwandpush.envs.pusher3dof2pixel import Pusher3Dof2PixelEnv
from gym_throwandpush.envs.pusher3dof2_inverse import Pusher3Dof2Inverse
from gym_throwandpush.envs.striker import StrikerEnv
from gym_throwandpush.envs.striker_backlash import StrikerEnv2
from gym_throwandpush.envs.striker_plus import StrikerPlus
from gym_throwandpush.envs.striker_lstm import StrikerLstm
from gym_throwandpush.envs.striker3dof import StrikerEnv3Dof
from gym_throwandpush.envs.striker3dof2 import StrikerEnv3Dof2
from gym_throwandpush.envs.thrower_backlash import ThrowerEnv
from gym_throwandpush.envs.thrower_plus import ThrowerPlus
